// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkstationInfo.Database;

#nullable disable

namespace WorkstationInfo.Migrations
{
    [DbContext(typeof(WorkstationInfoDbContext))]
    [Migration("20250311195354_AddWorkorderEventLogKey")]
    partial class AddWorkorderEventLogKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkstationInfo.Entities.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorId"));

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("SensorId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.Workorder", b =>
                {
                    b.Property<int>("WorkorderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkorderId"));

                    b.Property<string>("CurrentScodeValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaktTime")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("WorkorderId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("Workorders");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.WorkorderEventLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScodeValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkorderId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("WorkorderId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("WorkorderEventLogs");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.Workstation", b =>
                {
                    b.Property<int>("WorkstationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkstationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ScodeValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkstationId");

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.WorkstationPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Availability")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CycleTime")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Oee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Performance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quality")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("interval");

                    b.Property<int>("WorkorderId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkorderId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("WorkstationPerformances");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.Sensor", b =>
                {
                    b.HasOne("WorkstationInfo.Entities.Workstation", "Workstation")
                        .WithMany("Sensors")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.Workorder", b =>
                {
                    b.HasOne("WorkstationInfo.Entities.Workstation", "Workstation")
                        .WithMany("Workorders")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.WorkorderEventLog", b =>
                {
                    b.HasOne("WorkstationInfo.Entities.Workorder", "Workorder")
                        .WithMany("EventLogs")
                        .HasForeignKey("WorkorderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkstationInfo.Entities.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workorder");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.WorkstationPerformance", b =>
                {
                    b.HasOne("WorkstationInfo.Entities.Workorder", "Workorder")
                        .WithMany()
                        .HasForeignKey("WorkorderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkstationInfo.Entities.Workstation", "Workstation")
                        .WithMany("PerformanceRecords")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workorder");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.Workorder", b =>
                {
                    b.Navigation("EventLogs");
                });

            modelBuilder.Entity("WorkstationInfo.Entities.Workstation", b =>
                {
                    b.Navigation("PerformanceRecords");

                    b.Navigation("Sensors");

                    b.Navigation("Workorders");
                });
#pragma warning restore 612, 618
        }
    }
}
