// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MesAppDbContext))]
    partial class MesAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entities.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorId"));

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("SensorId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("sensor", "mes_db");
                });

            modelBuilder.Entity("Shared.Entities.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SensorTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SensorValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkorderId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sensor_data", "mes_db");
                });

            modelBuilder.Entity("Shared.Entities.SensorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sensor_types", "mes_db");
                });

            modelBuilder.Entity("Shared.Entities.Workorder", b =>
                {
                    b.Property<int>("WorkorderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkorderId"));

                    b.Property<int>("CurrentScodeValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaktTime")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("WorkorderId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workorder", "mes_db");
                });

            modelBuilder.Entity("Shared.Entities.WorkorderPerformanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Availability")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("CycleTime")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Oee")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Performance")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("Quality")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("interval");

                    b.Property<int>("WorkorderId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("total_net_available_time")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("total_net_operation_time")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("total_planned_downtime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("total_startup_downtime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("total_unplanned_downtime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("WorkorderId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workorder_performance_log", "mes_db");
                });

            modelBuilder.Entity("Shared.Entities.WorkorderStateLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedByOperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<int>("NewScodeId")
                        .HasColumnType("integer");

                    b.Property<int>("OldScodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("WorkorderId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkorderId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("workorder_state_log", "mes_db");
                });

            modelBuilder.Entity("Shared.Entities.Workstation", b =>
                {
                    b.Property<int>("WorkstationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkstationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkstationId");

                    b.ToTable("workstation", "mes_db");
                });

            modelBuilder.Entity("Shared.Entities.Sensor", b =>
                {
                    b.HasOne("Shared.Entities.Workstation", "Workstation")
                        .WithMany("Sensors")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Shared.Entities.Workorder", b =>
                {
                    b.HasOne("Shared.Entities.Workstation", "Workstation")
                        .WithMany("Workorders")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Shared.Entities.WorkorderPerformanceLog", b =>
                {
                    b.HasOne("Shared.Entities.Workorder", "Workorder")
                        .WithMany("PerformanceRecords")
                        .HasForeignKey("WorkorderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Entities.Workstation", "Workstation")
                        .WithMany("PerformanceRecords")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workorder");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Shared.Entities.WorkorderStateLog", b =>
                {
                    b.HasOne("Shared.Entities.Workorder", "Workorder")
                        .WithMany()
                        .HasForeignKey("WorkorderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Entities.Workstation", "Workstation")
                        .WithMany("StateLogs")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workorder");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Shared.Entities.Workorder", b =>
                {
                    b.Navigation("PerformanceRecords");
                });

            modelBuilder.Entity("Shared.Entities.Workstation", b =>
                {
                    b.Navigation("PerformanceRecords");

                    b.Navigation("Sensors");

                    b.Navigation("StateLogs");

                    b.Navigation("Workorders");
                });
#pragma warning restore 612, 618
        }
    }
}
